spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  #    hikari:
  #      schema: user_test
  #      minimum-idle: 1
  #    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    properties:
  #      hibernate:
  #        temp:
  #          use_jdbc_metadata_defaults: false
  #  sql:
  #    init:
  #      platform: postgres
  flyway:
    enabled: true
    schema: user_test
    locations: classpath:db/migration
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web